# Generated by Django 3.1.1 on 2020-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='info',
            field=models.CharField(default='0000000', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='publisher',
            field=models.CharField(max_length=500),
        ),
    ]
