# Generated by Django 3.1.1 on 2020-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201007_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
