# Generated by Django 3.1.1 on 2020-10-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201007_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('read', models.CharField(choices=[('B', 'Morning'), ('L', 'Noon'), ('D', 'Night')], default='B', max_length=1)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.comic')),
            ],
        ),
    ]
