# Generated by Django 3.1.1 on 2020-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_collectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='collectables',
            field=models.ManyToManyField(to='main_app.Collectable'),
        ),
    ]
