# Generated by Django 3.1.1 on 2020-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comic_collectables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='collectables',
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(verbose_name='reading date'),
        ),
    ]
